package com.misiontic2022.conversor;

// @author JuliandresCanon

public class Area extends javax.swing.JFrame {

    /**
     * Creates new form Area
     */
    public Area() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxOrigen = new javax.swing.JComboBox<>();
        ComboBoxDestino = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextValor = new javax.swing.JTextPane();
        TextRespuesta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("CONVERSOR DE AREAS");

        BotonVolver.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("De:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("A:");

        ComboBoxOrigen.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidades Origen ...", "mm2", "cm2", "m2", "km2" }));

        ComboBoxDestino.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidades Destino ...", "mm2", "cm2", "m2", "km2" }));

        TextValor.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(TextValor);

        TextRespuesta.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TextRespuesta.setText("...");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel4.setText("=");

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(ComboBoxOrigen, 0, 186, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxDestino, 0, 186, Short.MAX_VALUE)
                    .addComponent(TextRespuesta))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(BotonVolver)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonVolver)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextRespuesta)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        Principal ventana = new Principal();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        double res = 0.0;
        
        if (ComboBoxOrigen.getSelectedItem() == "mm2" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "mm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1 * 1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "cm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.1 * 0.1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "m2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.001 * 0.001;
                
            } else if (ComboBoxDestino.getSelectedItem() == "km2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.000001 * 0.000001;
                
            }
            
        } else if (ComboBoxOrigen.getSelectedItem() == "cm2" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "mm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 10 * 10;
                
            } else if (ComboBoxDestino.getSelectedItem() == "cm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1 * 1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "m2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.01 * 0.01;
                
            } else if (ComboBoxDestino.getSelectedItem() == "km2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.00001 * 0.00001;
                
            }
            
        } else if (ComboBoxOrigen.getSelectedItem() == "m2" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "mm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1000 * 1000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "cm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 100 * 100;
                
            } else if (ComboBoxDestino.getSelectedItem() == "m2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1 * 1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "km2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.001 * 0.001;
                
            }
            
        } else if (ComboBoxOrigen.getSelectedItem() == "km2" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "mm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1000000 * 1000000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "cm2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 100000 * 10000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "m2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1000 * 1000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "km2" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1 * 1;
                
            }
            
        }
        
        TextRespuesta.setText(String.valueOf(res));

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Area().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVolver;
    private javax.swing.JComboBox<String> ComboBoxDestino;
    private javax.swing.JComboBox<String> ComboBoxOrigen;
    private javax.swing.JTextField TextRespuesta;
    private javax.swing.JTextPane TextValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
