package com.misiontic2022.conversor;

import java.awt.image.ColorConvertOp;
import javax.management.StringValueExp;

// @author JuliandresCanon

public class Longitud extends javax.swing.JFrame {

    /**
     * Creates new form Longitud
     */
    public Longitud() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxOrigen = new javax.swing.JComboBox<>();
        ComboBoxDestino = new javax.swing.JComboBox<>();
        BotonVolver = new javax.swing.JButton();
        BotonCalcular = new javax.swing.JButton();
        TextRespuesta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextValor = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("De:");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("A:");

        ComboBoxOrigen.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidades Origen ...", "Milimetros", "Centimetros", "Metros", "Kilometros" }));
        ComboBoxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxOrigenActionPerformed(evt);
            }
        });

        ComboBoxDestino.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidades Destino ...", "Milimetros", "Centimetros", "Metros", "Kilometros" }));
        ComboBoxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDestinoActionPerformed(evt);
            }
        });

        BotonVolver.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        BotonCalcular.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        BotonCalcular.setText("Calcular");
        BotonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalcularActionPerformed(evt);
            }
        });

        TextRespuesta.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TextRespuesta.setText("...");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("CONVERSOR DE LONGITUDES");

        TextValor.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TextValor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(TextValor);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel4.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(BotonCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextRespuesta)
                    .addComponent(ComboBoxDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVolver)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextRespuesta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(BotonCalcular)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxOrigenActionPerformed

    private void ComboBoxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxDestinoActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        Principal ventana = new Principal();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalcularActionPerformed
        
        double res = 0.0;
        
        if (ComboBoxOrigen.getSelectedItem() == "Milimetros" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "Milimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Centimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Metros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.001;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Kilometros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.000001;
                
            }
            
        } else if (ComboBoxOrigen.getSelectedItem() == "Centimetros" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "Milimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 10;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Centimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Metros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.01;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Kilometros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.00001;
                
            }
            
        } else if (ComboBoxOrigen.getSelectedItem() == "Metros" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "Milimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Centimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 100;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Metros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Kilometros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 0.001;
                
            }
            
        } else if (ComboBoxOrigen.getSelectedItem() == "Kilometros" ) {
        
            if (ComboBoxDestino.getSelectedItem() == "Milimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1000000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Centimetros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 100000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Metros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1000;
                
            } else if (ComboBoxDestino.getSelectedItem() == "Kilometros" ) {
                int a = Integer.parseInt(TextValor.getText());
                res = a * 1;
                
            }
            
        }
        
        TextRespuesta.setText(String.valueOf(res));
    }//GEN-LAST:event_BotonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Longitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCalcular;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JComboBox<String> ComboBoxDestino;
    private javax.swing.JComboBox<String> ComboBoxOrigen;
    private javax.swing.JTextField TextRespuesta;
    private javax.swing.JTextPane TextValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private Object ComboBoxOrigen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
