/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EjerciciosClase;

/**
 *
 * @author JuliandresCanon
 */
public class EjerciciosClase extends javax.swing.JFrame {

    /**
     * Creates new form EjerciciosClase
     */
    public EjerciciosClase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPanel = new javax.swing.JTabbedPane();
        PanelPreg1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelSelecc1 = new javax.swing.JPanel();
        RBFalso = new javax.swing.JRadioButton();
        RBVerdadero = new javax.swing.JRadioButton();
        PanelPreg2 = new javax.swing.JPanel();
        PanelPreg3 = new javax.swing.JPanel();
        PanelPreg4 = new javax.swing.JPanel();
        PanelResp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1. Hoy es el ultimo viernes de Julio.");

        RBFalso.setText("Falso");

        RBVerdadero.setText("Verdadero");

        javax.swing.GroupLayout PanelSelecc1Layout = new javax.swing.GroupLayout(PanelSelecc1);
        PanelSelecc1.setLayout(PanelSelecc1Layout);
        PanelSelecc1Layout.setHorizontalGroup(
            PanelSelecc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecc1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSelecc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBVerdadero)
                    .addComponent(RBFalso))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PanelSelecc1Layout.setVerticalGroup(
            PanelSelecc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelecc1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(RBVerdadero)
                .addGap(18, 18, 18)
                .addComponent(RBFalso)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPreg1Layout = new javax.swing.GroupLayout(PanelPreg1);
        PanelPreg1.setLayout(PanelPreg1Layout);
        PanelPreg1Layout.setHorizontalGroup(
            PanelPreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPreg1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelPreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSelecc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        PanelPreg1Layout.setVerticalGroup(
            PanelPreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPreg1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PanelSelecc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        TabbedPanel.addTab("Pregunta 1", PanelPreg1);

        javax.swing.GroupLayout PanelPreg2Layout = new javax.swing.GroupLayout(PanelPreg2);
        PanelPreg2.setLayout(PanelPreg2Layout);
        PanelPreg2Layout.setHorizontalGroup(
            PanelPreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        PanelPreg2Layout.setVerticalGroup(
            PanelPreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        TabbedPanel.addTab("Pregunta 2", PanelPreg2);

        javax.swing.GroupLayout PanelPreg3Layout = new javax.swing.GroupLayout(PanelPreg3);
        PanelPreg3.setLayout(PanelPreg3Layout);
        PanelPreg3Layout.setHorizontalGroup(
            PanelPreg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        PanelPreg3Layout.setVerticalGroup(
            PanelPreg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        TabbedPanel.addTab("Pregunta 3", PanelPreg3);

        javax.swing.GroupLayout PanelPreg4Layout = new javax.swing.GroupLayout(PanelPreg4);
        PanelPreg4.setLayout(PanelPreg4Layout);
        PanelPreg4Layout.setHorizontalGroup(
            PanelPreg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        PanelPreg4Layout.setVerticalGroup(
            PanelPreg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        TabbedPanel.addTab("Pregunta 4", PanelPreg4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Resultados");

        javax.swing.GroupLayout PanelRespLayout = new javax.swing.GroupLayout(PanelResp);
        PanelResp.setLayout(PanelRespLayout);
        PanelRespLayout.setHorizontalGroup(
            PanelRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRespLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(512, Short.MAX_VALUE))
        );
        PanelRespLayout.setVerticalGroup(
            PanelRespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRespLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        TabbedPanel.addTab("Respuesta", PanelResp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjerciciosClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjerciciosClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjerciciosClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjerciciosClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjerciciosClase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPreg1;
    private javax.swing.JPanel PanelPreg2;
    private javax.swing.JPanel PanelPreg3;
    private javax.swing.JPanel PanelPreg4;
    private javax.swing.JPanel PanelResp;
    private javax.swing.JPanel PanelSelecc1;
    private javax.swing.JRadioButton RBFalso;
    private javax.swing.JRadioButton RBVerdadero;
    private javax.swing.JTabbedPane TabbedPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
