/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.misiontic2022.alumnos;

/**
 *
 * @author JuliandresCanon
 */
public class Alumnos extends javax.swing.JFrame {

    /**
     * Creates new form Alumnos
     */
    public Alumnos() {
        initComponents();
    }
     public String nombres;
     public String apellidos;
     public int anioDeNacimiento;
     public int numeroPersonal;
     public int grupo;
     public String turnoHorario;

    public Alumnos(String nombres, String apellidos, int anioDeNacimiento, int numeroPersonal, int grupo, String turnoHorario) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.anioDeNacimiento = anioDeNacimiento;
        this.numeroPersonal = numeroPersonal;
        this.grupo = grupo;
        this.turnoHorario = turnoHorario;
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LabelNombres = new javax.swing.JLabel();
        LabelApellidos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPaneNombres = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPaneApellidos = new javax.swing.JTextPane();
        LabelAnioNacimiento = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextPaneAnioNacimiento = new javax.swing.JTextPane();
        LabelNumero = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextPaneNumero = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextPaneGrupo = new javax.swing.JTextPane();
        LabelGrupo = new javax.swing.JLabel();
        LabelJornada = new javax.swing.JLabel();
        ComboBoxJornada = new javax.swing.JComboBox<>();
        ButtonSalir = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelTitulo1 = new javax.swing.JLabel();
        LabelNumero2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextPaneBusquedaNumero = new javax.swing.JTextPane();
        ButtonBuscar = new javax.swing.JButton();
        LabelNuevoGrupo = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextPaneCambiarGrupo = new javax.swing.JTextPane();
        ButtonCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        LabelTitulo.setText("LISTA DE ALUMNOS");

        LabelNombres.setText("Nombres:");

        LabelApellidos.setText("Apellidos:");

        jScrollPane1.setViewportView(TextPaneNombres);

        jScrollPane2.setViewportView(TextPaneApellidos);

        LabelAnioNacimiento.setText("Año Nacimiento:");

        jScrollPane3.setViewportView(TextPaneAnioNacimiento);

        LabelNumero.setText("Número:");

        jScrollPane4.setViewportView(TextPaneNumero);

        jScrollPane5.setViewportView(TextPaneGrupo);

        LabelGrupo.setText("Grupo:");

        LabelJornada.setText("Jornada:");

        ComboBoxJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ...", "Mañana", "Tarde" }));

        ButtonSalir.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        ButtonSalir.setText("SALIR");

        ButtonGuardar.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        ButtonGuardar.setText("GUARDAR");

        LabelTitulo1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        LabelTitulo1.setText("BUSQUEDA DE ALUMNOS");

        LabelNumero2.setText("Número:");

        jScrollPane6.setViewportView(TextPaneBusquedaNumero);

        ButtonBuscar.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        ButtonBuscar.setText("BUSCAR");

        LabelNuevoGrupo.setText("Nuevo Grupo:");

        jScrollPane7.setViewportView(TextPaneCambiarGrupo);

        ButtonCambiar.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        ButtonCambiar.setText("CAMBIAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelTitulo)
                        .addGap(47, 47, 47)
                        .addComponent(ButtonSalir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAnioNacimiento)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(LabelApellidos)
                                    .addGap(42, 42, 42))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(LabelNumero)
                                    .addGap(47, 47, 47))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelNombres)
                                        .addComponent(LabelGrupo)
                                        .addComponent(LabelJornada))
                                    .addGap(42, 42, 42))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(ComboBoxJornada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelTitulo1)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNumero2)
                            .addComponent(LabelNuevoGrupo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(LabelTitulo))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNombres)
                        .addGap(26, 26, 26)
                        .addComponent(LabelApellidos)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelAnioNacimiento)
                        .addGap(26, 26, 26)
                        .addComponent(LabelNumero)
                        .addGap(26, 26, 26)
                        .addComponent(LabelGrupo)
                        .addGap(26, 26, 26)
                        .addComponent(LabelJornada))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelNumero2)
                            .addGap(8, 8, 8))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelNuevoGrupo)
                            .addGap(8, 8, 8))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumnos().setVisible(true);
            }
        });
    }
    
    
    // CREACION DE METODOS
    
    public void cambiaGrupo() {
        
    }
    
    public void asignaValores() {
        
    }
    
    public void muestraGrupo() {
        
    }
    
    public void dameGrupo() {
        
    }
    
    public void esMayorEdad() {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonCambiar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JComboBox<String> ComboBoxJornada;
    private javax.swing.JLabel LabelAnioNacimiento;
    private javax.swing.JLabel LabelApellidos;
    private javax.swing.JLabel LabelGrupo;
    private javax.swing.JLabel LabelJornada;
    private javax.swing.JLabel LabelNombres;
    private javax.swing.JLabel LabelNuevoGrupo;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelNumero2;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTitulo1;
    private javax.swing.JTextPane TextPaneAnioNacimiento;
    private javax.swing.JTextPane TextPaneApellidos;
    private javax.swing.JTextPane TextPaneBusquedaNumero;
    private javax.swing.JTextPane TextPaneCambiarGrupo;
    private javax.swing.JTextPane TextPaneGrupo;
    private javax.swing.JTextPane TextPaneNombres;
    private javax.swing.JTextPane TextPaneNumero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
